-- MySQL Script generated by MySQL Workbench
-- 04/13/17 23:54:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
use u121456690_exam;
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserSecurity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserSecurity` (
  `userID` INT NOT NULL,
  `passwordHash` VARCHAR(120) NULL,
  `verificationHash` VARCHAR(120) NULL,
  PRIMARY KEY (`userID`),
  CONSTRAINT `userSecurity`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Roles` (
  `role` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserRoles` (
  `role` VARCHAR(100) NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`role`, `userID`),
  INDEX `user_idx` (`userID` ASC),
  CONSTRAINT `userRole`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roleUser`
    FOREIGN KEY (`role`)
    REFERENCES `Roles` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Orders` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NULL,
  `deliveryDate` VARCHAR(45) NULL,
  `deliveryTime` VARCHAR(45) NULL,
  PRIMARY KEY (`orderID`),
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShippingAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShippingAddress` (
  `orderID` INT NOT NULL,
  `street` VARCHAR(90) NULL,
  `zipcode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  PRIMARY KEY (`orderID`),
  CONSTRAINT `orderIDShipping`
    FOREIGN KEY (`orderID`)
    REFERENCES `Orders` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InvoiceAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvoiceAddress` (
  `orderID` INT NOT NULL,
  `street` VARCHAR(90) NULL,
  `zipcode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  PRIMARY KEY (`orderID`),
  CONSTRAINT `OrderInvoice`
    FOREIGN KEY (`orderID`)
    REFERENCES `Orders` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(150) NULL,
  `productPrice` FLOAT NULL,
  `productWheelDiameter` VARCHAR(45) NULL,
  `productFrameSize` VARCHAR(45) NULL,
  `productAgeRange` VARCHAR(45) NULL,
  `productDescription` VARCHAR(250) NULL,
  `productBrand` VARCHAR(100) NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Item` (
  `itemID` INT NOT NULL AUTO_INCREMENT,
  `productID` INT NULL,
  PRIMARY KEY (`itemID`),
  INDEX `Product_idx` (`productID` ASC),
  CONSTRAINT `ProductItem`
    FOREIGN KEY (`productID`)
    REFERENCES `Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrderDetails` (
  `orderID` INT NOT NULL,
  `itemID` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`orderID`, `itemID`),
  INDEX `Item_idx` (`itemID` ASC),
  CONSTRAINT `OrderDetails`
    FOREIGN KEY (`orderID`)
    REFERENCES `Orders` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ItemDetails`
    FOREIGN KEY (`itemID`)
    REFERENCES `Item` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductAttributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductAttributes` (
  `productID` INT NOT NULL,
  `attribute` VARCHAR(250) NULL,
  `ProductAttributescol` VARCHAR(45) NULL,
  PRIMARY KEY (`productID`),
  CONSTRAINT `ProductAttributes`
    FOREIGN KEY (`productID`)
    REFERENCES `Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Category` (
  `category` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  PRIMARY KEY (`category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductInCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductInCategory` (
  `productID` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`productID`, `category`),
  INDEX `category_idx` (`category` ASC),
  CONSTRAINT `productInCategory`
    FOREIGN KEY (`productID`)
    REFERENCES `Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoryPerProduct`
    FOREIGN KEY (`category`)
    REFERENCES `Category` (`category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Requests` (
  `userID` INT NOT NULL,
  `productID` INT NOT NULL,
  `reason` VARCHAR(250) NULL,
  `Requestscol` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`, `productID`),
  INDEX `product_idx` (`productID` ASC),
  CONSTRAINT `userRequest`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productRequest`
    FOREIGN KEY (`productID`)
    REFERENCES `Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductImages` (
  `productID` INT NOT NULL,
  `image` VARCHAR(250) NULL,
  `ProductImagescol` VARCHAR(45) NULL,
  PRIMARY KEY (`productID`),
  CONSTRAINT `productImages`
    FOREIGN KEY (`productID`)
    REFERENCES `Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
